# Generated by Django 4.2.6 on 2023-11-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
