# Generated by Django 4.2.6 on 2023-11-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_spending_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFinances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='spending',
            name='income',
        ),
    ]
